### ISSUE TITLE
mockModule provide API

### ISSUE THREAD

**Issue by dmkc** [EventMobi/angular-easy-test#1]
Oh hi!

So, we talked about supplying hashes to `mockModule` instead of arrays but what I've realized is that sometimes you want to provide something other than a factory. `$provide` is able to mock out more than factories: https://docs.angularjs.org/api/auto/service/$provide

The current `provider` syntax is technically a misnomer. E.g. 
```javascript
EasyTest.mockModule('blah', [{ name: 'SomeService',  provider: myService }])
```
is actually calling `$provide.factory`, not `$provide.provider`. I propose the following changes: first, extend the current API to be able to mock out whatever `$provide` is able to:

```javascript
// Mock out a factory
EasyTest.mockModule('blah', [{ name: 'SomeService',  factory: myService }])

// Mock out a value
EasyTest.mockModule('blah', [{ name: 'SomeValue',  value: myValue }])

// Mock out a provider-provider, not a factory
EasyTest.mockModule('blah', [{ name: 'SomeService',  provider: myService }])
```
The latter case, specifically `$provide.value`, is what I needed to properly mock out `$q` using node's implementation, as it is not a factory but merely a straight-up library.

In addition to that, and assuming that factories are the most common use case (I don't know if they are), we can let the library take a hash instead:
```javascript
// Take a hash of factories
EasyTest.mockModule('myHotModule', {
  'ServiceToMock': myMockService, 
  'AnotherService': anotherMock
})
```
which will be equivalent to using `factory: myMockService`, or `$provide.factory` under the hood.

Whatcha think?

**Comment by RickEyre** [comment]
@dmkc if you haven't had time to work on this I'd like to take it over?
